{
	"version": 1544749930,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bplay-sheet0.png",
		"images/bconfiguracao-sheet0.png",
		"images/bmusica-sheet0.png",
		"images/bsom-sheet0.png",
		"images/btrofeu-sheet0.png",
		"images/feminino-sheet0.png",
		"images/masculino-sheet0.png",
		"images/avancar-sheet0.png",
		"images/avancar-sheet1.png",
		"images/bhome-sheet0.png",
		"images/bpausa-sheet0.png",
		"images/hud-sheet0.png",
		"images/breturn-sheet0.png",
		"images/bfechar-sheet0.png",
		"images/bidioma-sheet0.png",
		"images/bidioma-sheet1.png",
		"images/txtcréditos-sheet0.png",
		"images/txtcréditos-sheet1.png",
		"images/criadortexto-sheet0.png",
		"images/bfases-sheet0.png",
		"images/bfases-sheet1.png",
		"images/fasecompleta-sheet0.png",
		"images/fasecompleta-sheet1.png",
		"images/personagem-sheet0.png",
		"images/personagem-sheet1.png",
		"images/bapagaragenda-sheet0.png",
		"images/agenda1-sheet0.png",
		"images/bapagaragenda2-sheet0.png",
		"images/agenda3-sheet0.png",
		"images/bapagaragenda3-sheet0.png",
		"images/agenda4-sheet0.png",
		"images/agenda4-sheet1.png",
		"images/bapagaragenda4-sheet0.png",
		"images/agenda5-sheet0.png",
		"images/agenda6-sheet0.png",
		"images/agenda7-sheet0.png",
		"images/agenda8-sheet0.png",
		"images/agenda9-sheet0.png",
		"images/bg-sheet0.png",
		"images/clientefase2-sheet0.png",
		"images/respostafase2pt-sheet0.png",
		"images/perguntafinalfase1-sheet0.png",
		"images/respostafinalfase1port-sheet0.png",
		"images/perguntafinalfase2-sheet0.png",
		"images/respostafinalfase2pt-sheet0.png",
		"images/perguntafinalfase3-sheet0.png",
		"images/respostafinalfase3pt-sheet0.png",
		"images/perguntafinalfase4-sheet0.png",
		"images/respostafinalfase4pt-sheet0.png",
		"images/perguntafinalfase5-sheet0.png",
		"images/respostafinalfase5pt-sheet0.png",
		"images/perguntafinalfase6-sheet0.png",
		"images/respostafinalfase6pt-sheet0.png",
		"images/perguntafinalfase7-sheet0.png",
		"images/respostafinalfase7-sheet0.png",
		"images/respostafinalfase8pt-sheet0.png",
		"images/perguntafinalfase8-sheet0.png",
		"images/passarfase2-sheet0.png",
		"images/iconesfase3-sheet0.png",
		"images/iconesfase3-sheet1.png",
		"images/fundo-sheet0.png",
		"images/principal1-sheet0.png",
		"images/principal2-sheet0.png",
		"images/principal3-sheet0.png",
		"images/principal4-sheet0.png",
		"images/produto-sheet0.png",
		"images/produto-sheet1.png",
		"images/prateleira-sheet0.png",
		"images/iconeproduto1-sheet0.png",
		"images/iconeproduto1-sheet1.png",
		"images/iconeproduto2-sheet0.png",
		"images/dinheirototalvalor.png",
		"images/calderaofase5-sheet0.png",
		"images/tempofase5e6-sheet0.png",
		"images/fruta1fase5-sheet0.png",
		"images/iconefrutasfase5-sheet0.png",
		"images/iconefrutasfase5-sheet1.png",
		"images/frutasfase6mouse-sheet0.png",
		"images/fruta2fase5-sheet0.png",
		"images/fruta3fase5-sheet0.png",
		"images/fruta4fase5-sheet0.png",
		"images/fruta5fase5-sheet0.png",
		"images/fruta6fase5-sheet0.png",
		"images/chao-sheet0.png",
		"images/cliente1-sheet0.png",
		"images/personagensfase6-sheet0.png",
		"images/personagensfase6-sheet1.png",
		"images/pratodesejado-sheet0.png",
		"images/pratodesejado-sheet1.png",
		"images/pratodesejado-sheet2.png",
		"images/humorfase7-sheet0.png",
		"images/humor2-sheet0.png",
		"images/humor2-sheet1.png",
		"images/humor2-sheet2.png",
		"images/personagemtela-sheet0.png",
		"images/personagemmtela-sheet0.png",
		"images/logo-sheet0.png",
		"images/tiledceu.png",
		"images/restaurante-sheet0.png",
		"images/telaselecao-sheet0.png",
		"images/socios-sheet0.png",
		"images/socios-sheet1.png",
		"images/iconesfase-sheet0.png",
		"images/iconesfase-sheet1.png",
		"images/iconesfase33-sheet0.png",
		"images/iconesfase333-sheet0.png",
		"images/iconesfase333-sheet1.png",
		"images/voltarpersonagem-sheet0.png",
		"images/bccasas-sheet0.png",
		"images/fundoagenda-sheet0.png",
		"images/bgagenda-sheet0.png",
		"images/txttelaintro-sheet0.png",
		"images/iconerestfase1-sheet0.png",
		"images/tbcmurofase2.png",
		"images/tbcchaofase2.png",
		"images/dinheirogastonumero.png",
		"images/dinheirosobra.png",
		"images/fogofase5-sheet0.png",
		"images/fogãofase5-sheet0.png",
		"images/prateleiraa-sheet0.png",
		"images/fruta8fase5-sheet0.png",
		"images/fruta7fase5-sheet0.png",
		"images/bpassarfase5-sheet0.png",
		"images/bgfase6-sheet0.png",
		"images/mesa1fase6-sheet0.png",
		"images/bancofase6-sheet0.png",
		"images/personagem1fase2-sheet0.png",
		"images/personagensfase1-sheet0.png",
		"images/personagem2fase2-sheet0.png",
		"images/personagensfase2-sheet0.png",
		"images/personagensfase2-sheet1.png",
		"images/personagensfase2-sheet2.png",
		"images/personagem1fase3-sheet0.png",
		"images/personagem2fase3-sheet0.png",
		"images/personagem3fase3-sheet0.png",
		"images/personagem4fase3-sheet0.png",
		"images/fundonarrativa-sheet0.png",
		"images/personagemnarrativa-sheet0.png",
		"images/balaonarrativapt-sheet0.png",
		"images/balaonarrativapt-sheet1.png",
		"images/balaonarrativaen-sheet0.png",
		"images/balaonarrativaen-sheet1.png",
		"images/fundocozinha-sheet0.png",
		"images/tiledbackground.png",
		"images/fundofasedecompras-sheet0.png",
		"images/prateleiraunidade-sheet0.png",
		"images/quadro-sheet0.png",
		"images/precodascompras-sheet0.png",
		"images/precodascompras-sheet1.png",
		"images/precodascompras-sheet2.png",
		"images/dinheirototaltxt_pt.png",
		"images/cartazdivulgacaoen-sheet0.png",
		"images/cartazdivulgacaoen-sheet1.png",
		"images/icone1fase5-sheet0.png",
		"images/iconecomidafase6-sheet0.png",
		"images/iconecomidafase6-sheet1.png",
		"images/iconecomidafase6-sheet2.png",
		"images/comida1arrastar-sheet0.png",
		"images/comida1arrastar-sheet1.png",
		"images/comida2arrastar-sheet0.png",
		"images/comida3arrastar-sheet0.png",
		"images/pratodesejado2-sheet0.png",
		"images/pratodesejado2-sheet1.png",
		"images/pratodesejado2-sheet2.png",
		"images/mesa2fase6-sheet0.png",
		"images/iconesfase8-sheet0.png",
		"images/iconesfase8-sheet1.png",
		"images/iconesfase8-sheet2.png",
		"images/escolhacartaz-sheet0.png",
		"images/escolhapersonagem-sheet0.png",
		"images/personagemsociosfase7-sheet0.png",
		"images/caixaperguntaa-sheet0.png",
		"images/caixaperguntab-sheet0.png",
		"images/caixaperguntac-sheet0.png",
		"images/respostafinalfase1en-sheet0.png",
		"images/respostafinalfase2en-sheet0.png",
		"images/respostafinalfase3en-sheet0.png",
		"images/respostafinalfase4en-sheet0.png",
		"images/respostafinalfase5en-sheet0.png",
		"images/respostafinalfase7en-sheet0.png",
		"images/respostafinalfase8en-sheet0.png",
		"images/respostafinalfase6en-sheet0.png",
		"images/conceitocanvas-sheet0.png",
		"images/bsaidocanvas-sheet0.png",
		"images/canvascompleto-sheet0.png",
		"images/canvascompleto-sheet1.png",
		"images/fundocanvascompleto-sheet0.png",
		"images/passarcreditos-sheet0.png",
		"images/iconeagendas-sheet0.png",
		"images/iconeagendas-sheet1.png",
		"images/iconeagendas-sheet2.png",
		"images/quadrofase4-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/blocofase6-sheet0.png",
		"images/blocofase6-sheet1.png",
		"images/faixafase8-sheet0.png",
		"images/iconesfase8en-sheet0.png",
		"images/iconesfase8en-sheet1.png",
		"images/iconesfase8en-sheet2.png",
		"images/dinheirototaltxt_en.png",
		"images/dinheirogastotxt_en.png",
		"images/fundopretofaseok-sheet0.png",
		"images/cartazdivulgacaopt-sheet0.png",
		"images/cartazdivulgacaopt-sheet1.png",
		"images/cartazdivulgacaopt-sheet2.png",
		"images/encolorido-sheet0.png",
		"images/fundosozinho-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tituloagendafases-sheet0.png",
		"images/tituloagendafasesen-sheet0.png",
		"images/tituloagendafasesen-sheet1.png",
		"images/perguntamecanicafase1-sheet0.png",
		"images/respostasfase1mecanicaen-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/letreirooo-sheet0.png",
		"images/personagemnojogo-sheet0.png",
		"images/personagemnojogo-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/tenteoutravezfase8-sheet0.png",
		"images/tenteoutravezfase8-sheet1.png",
		"media/acertar pergunta.m4a",
		"media/acertar pergunta.ogg",
		"media/acerto icone fases.m4a",
		"media/acerto icone fases.ogg",
		"media/agenda.m4a",
		"media/agenda.ogg",
		"media/audio pergunta errada.m4a",
		"media/audio pergunta errada.ogg",
		"media/fazendo a comida.m4a",
		"media/fazendo a comida.ogg",
		"media/fazendo compras.m4a",
		"media/fazendo compras.ogg",
		"media/menu, escolha personagem e narrativa (1).m4a",
		"media/menu, escolha personagem e narrativa (1).ogg",
		"media/na rua.m4a",
		"media/na rua.ogg",
		"media/pergunta final da fase.m4a",
		"media/pergunta final da fase.ogg",
		"media/servir clientes.m4a",
		"media/servir clientes.ogg",
		"media/tempo acabou.m4a",
		"media/tempo acabou.ogg",
		"media/sistema de fases.m4a",
		"media/sistema de fases (online-audio-converter.com).m4a",
		"media/sistema de fases (online-audio-converter.com).ogg",
		"media/audio pergunta final corte.m4a",
		"media/audio pergunta final corte.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}